# data =[ 
# ('addx', 15),
# ('addx', -11),
# ('addx', 6),
# ('addx', -3),
# ('addx', 5),
# ('addx', -1),
# ('addx', -8),
# ('addx', 13),
# ('addx', 4),
# ('noop',None),
# ('addx', -1),
# ('addx', 5),
# ('addx', -1),
# ('addx', 5),
# ('addx', -1),
# ('addx', 5),
# ('addx', -1),
# ('addx', 5),
# ('addx', -1),
# ('addx', -35),
# ('addx', 1),
# ('addx', 24),
# ('addx', -19),
# ('addx', 1),
# ('addx', 16),
# ('addx', -11),
# ('noop',None),
# ('noop',None),
# ('addx', 21),
# ('addx', -15),
# ('noop',None),
# ('noop',None),
# ('addx', -3),
# ('addx', 9),
# ('addx', 1),
# ('addx', -3),
# ('addx', 8),
# ('addx', 1),
# ('addx', 5),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', -36),
# ('noop',None),
# ('addx', 1),
# ('addx', 7),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', 2),
# ('addx', 6),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', 1),
# ('noop',None),
# ('noop',None),
# ('addx', 7),
# ('addx', 1),
# ('noop',None),
# ('addx', -13),
# ('addx', 13),
# ('addx', 7),
# ('noop',None),
# ('addx', 1),
# ('addx', -33),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', 2),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', 8),
# ('noop',None),
# ('addx', -1),
# ('addx', 2),
# ('addx', 1),
# ('noop',None),
# ('addx', 17),
# ('addx', -9),
# ('addx', 1),
# ('addx', 1),
# ('addx', -3),
# ('addx', 11),
# ('noop',None),
# ('noop',None),
# ('addx', 1),
# ('noop',None),
# ('addx', 1),
# ('noop',None),
# ('noop',None),
# ('addx', -13),
# ('addx', -19),
# ('addx', 1),
# ('addx', 3),
# ('addx', 26),
# ('addx', -30),
# ('addx', 12),
# ('addx', -1),
# ('addx', 3),
# ('addx', 1),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', -9),
# ('addx', 18),
# ('addx', 1),
# ('addx', 2),
# ('noop',None),
# ('noop',None),
# ('addx', 9),
# ('noop',None),
# ('noop',None),
# ('noop',None),
# ('addx', -1),
# ('addx', 2),
# ('addx', -37),
# ('addx', 1),
# ('addx', 3),
# ('noop',None),
# ('addx', 15),
# ('addx', -21),
# ('addx', 22),
# ('addx', -6),
# ('addx', 1),
# ('noop',None),
# ('addx', 2),
# ('addx', 1),
# ('noop',None),
# ('addx', -10),
# ('noop',None),
# ('noop',None),
# ('addx', 20),
# ('addx', 1),
# ('addx', 2),
# ('addx', 2),
# ('addx', -6),
# ('addx', -11),
# ('noop',None),
# ('noop',None),
# ('noop',None)]

data = [('addx', 1),
('noop', None),
('addx', 4),
('noop', None),
('noop', None),
('noop', None),
('addx', 6),
('addx', -1),
('addx', 5),
('noop', None),
('noop', None),
('noop', None),
('addx', 5),
('addx', -14),
('noop', None),
('addx', 19),
('noop', None),
('addx', 1),
('addx', 4),
('addx', 1),
('noop', None),
('noop', None),
('addx', 2),
('addx', 5),
('addx', -27),
('addx', 20),
('addx', -30),
('addx', 2),
('addx', 5),
('addx', 2),
('addx', 4),
('addx', -3),
('addx', 2),
('addx', 5),
('addx', 2),
('addx', -9),
('addx', 1),
('addx', 11),
('noop', None),
('addx', -20),
('addx', 7),
('addx', 23),
('addx', 2),
('addx', 3),
('addx', -2),
('addx', -34),
('addx', -2),
('noop', None),
('addx', 3),
('noop', None),
('addx', 3),
('addx', 2),
('noop', None),
('addx', 3),
('addx', 2),
('addx', 5),
('addx', 2),
('addx', -9),
('addx', -7),
('addx', 21),
('noop', None),
('addx', 8),
('noop', None),
('addx', -1),
('addx', 3),
('addx', -2),
('addx', 5),
('addx', -37),
('noop', None),
('addx', 35),
('addx', -31),
('addx', 1),
('addx', 4),
('addx', -1),
('addx', 2),
('noop', None),
('addx', 3),
('addx', 1),
('addx', 5),
('addx', -2),
('addx', 7),
('addx', -2),
('addx', -2),
('addx', 10),
('noop', None),
('addx', 4),
('noop', None),
('noop', None),
('addx', -19),
('addx', 20),
('addx', -38),
('noop', None),
('noop', None),
('addx', 7),
('addx', 2),
('addx', 3),
('noop', None),
('addx', 4),
('addx', -3),
('addx', 2),
('addx', 2),
('noop', None),
('addx', 3),
('noop', None),
('noop', None),
('noop', None),
('addx', 5),
('noop', None),
('addx', 7),
('addx', -2),
('addx', 7),
('noop', None),
('noop', None),
('addx', -5),
('addx', 6),
('addx', -36),
('noop', None),
('addx', 1),
('addx', 2),
('addx', 5),
('addx', 2),
('addx', 3),
('addx', -2),
('addx', 2),
('addx', 5),
('addx', 2),
('addx', 1),
('noop', None),
('addx', 4),
('addx', -16),
('addx', 21),
('noop', None),
('noop', None),
('addx', 1),
('addx', -8),
('addx', 12),
('noop', None),
('noop', None),
('noop', None),
('noop', None)]