# data = {'AA': {'rate': 0, 'connected':['DD', 'II', 'BB']},
# 'BB': {'rate': 13, 'connected':['CC', 'AA']},
# 'CC': {'rate': 2, 'connected':['DD', 'BB']},
# 'DD': {'rate': 20, 'connected':['CC', 'AA', 'EE']},
# 'EE': {'rate': 3, 'connected':['FF', 'DD']},
# 'FF': {'rate': 0, 'connected':['EE', 'GG']},
# 'GG': {'rate': 0, 'connected':['FF', 'HH']},
# 'HH': {'rate': 22, 'connected':['GG']},
# 'II': {'rate': 0, 'connected':['AA', 'JJ']},
# 'JJ': {'rate': 21, 'connected':['II']},
# }
data = {'AW': {'rate': 0, 'connected': ['LG', 'TL']},
 'OM': {'rate': 0, 'connected': ['XK', 'IM']},
 'BG': {'rate': 0, 'connected': ['MP', 'SB']},
 'XB': {'rate': 0, 'connected': ['MA', 'TL']},
 'CD': {'rate': 0, 'connected': ['VL', 'OF']},
 'VF': {'rate': 0, 'connected': ['CS', 'XK']},
 'HK': {'rate': 0, 'connected': ['RL', 'QB']},
 'QN': {'rate': 0, 'connected': ['IV', 'QR']},
 'OF': {'rate': 4, 'connected': ['TQ', 'CD', 'IR', 'IM', 'JE']},
 'QB': {'rate': 14, 'connected': ['HK', 'XE', 'CS', 'VO']},
 'ZE': {'rate': 7, 'connected': ['JB', 'NC', 'SE', 'OI']},
 'OW': {'rate': 0, 'connected': ['MB', 'JB']},
 'MA': {'rate': 0, 'connected': ['XB', 'MB']},
 'MP': {'rate': 0, 'connected': ['VK', 'BG']},
 'UE': {'rate': 9, 'connected': ['ZM', 'RZ', 'WI', 'HO', 'FO']},
 'QR': {'rate': 24, 'connected': ['QN']},
 'TQ': {'rate': 0, 'connected': ['OF', 'AA']},
 'SE': {'rate': 0, 'connected': ['ZE', 'ZZ']},
 'AQ': {'rate': 20, 'connected': ['CX']},
 'XE': {'rate': 0, 'connected': ['JQ', 'QB']},
 'DC': {'rate': 8, 'connected': ['ZD', 'MJ', 'RZ']},
 'ZM': {'rate': 0, 'connected': ['YJ', 'UE']},
 'VK': {'rate': 21,'connected': ['MP']},
 'VR': {'rate': 0, 'connected': ['WV', 'PS']},
 'BH': {'rate': 0, 'connected': ['AA', 'MB']},
 'ZR': {'rate': 0, 'connected': ['LG', 'AI']},
 'JE': {'rate': 0, 'connected': ['OF', 'HO']},
 'IR': {'rate': 0, 'connected': ['IV', 'OF']},
 'FO': {'rate': 0, 'connected': ['XQ', 'UE']},
 'AA': {'rate': 0, 'connected': ['NC', 'VY', 'BH', 'TQ', 'YJ']},
 'ZZ': {'rate': 0, 'connected': ['SE', 'TL']},
 'XQ': {'rate': 0, 'connected': ['IV', 'FO']},
 'WI': {'rate': 0, 'connected': ['UE', 'VO']},
 'VY': {'rate': 0, 'connected': ['AA', 'LG']},
 'XK': {'rate': 15, 'connected': ['VF', 'OM', 'ZD']},
 'CX': {'rate': 0, 'connected': ['AQ', 'MB']},
 'JQ': {'rate': 0, 'connected': ['XE', 'IV']},
 'LG': {'rate': 3, 'connected': ['VY', 'PS', 'ZR', 'AW', 'OI']},
 'JB': {'rate': 0, 'connected': ['ZE', 'OW']},
 'OI': {'rate': 0, 'connected': ['ZE', 'LG']},
 'YJ': {'rate': 0, 'connected': ['ZM', 'AA']},
 'NC': {'rate': 0, 'connected': ['AA', 'ZE']},
 'KR': {'rate': 0, 'connected': ['SB', 'MJ']},
 'MB': {'rate': 17, 'connected': ['CX', 'BH', 'AI', 'OW', 'MA']},
 'AI': {'rate': 0, 'connected': ['ZR', 'MB']},
 'TL': {'rate': 16, 'connected': ['ZZ', 'XB', 'AW']},
 'RL': {'rate': 0, 'connected': ['WV', 'HK']},
 'CS': {'rate': 0, 'connected': ['VF', 'QB']},
 'WV': {'rate': 25, 'connected': ['RL', 'VL', 'VR']},
 'ZD': {'rate': 0, 'connected': ['XK', 'DC']},
 'IV': {'rate': 23, 'connected': ['XQ', 'IR', 'JQ', 'QN']},
 'PS': {'rate': 0, 'connected': ['VR', 'LG']},
 'RZ': {'rate': 0, 'connected': ['DC', 'UE']},
 'VO': {'rate': 0, 'connected': ['WI', 'QB']},
 'MJ': {'rate': 0, 'connected': ['DC', 'KR']},
 'IM': {'rate': 0, 'connected': ['OM', 'OF']},
 'VL': {'rate': 0, 'connected': ['CD', 'WV']},
 'SB': {'rate': 18, 'connected': ['BG', 'KR']},
 'HO': {'rate': 0, 'connected': ['JE', 'UE']}, }
